
# Experiment Setup, Logging Specifications, Environment
experiment:
  description: |

    > Experiment for 3D segmentation fine-tuning. 
  id: "(may2)fullsup_colon_dce_r1"     # for wandb run identification
  name: 'finetune'   # for experiment module identification
  project: '3DSeg-Pretrain'
  debug:                                            # (Correct Alignment)
    mode: False                                     # < Check
    overfitbatch: False                             # < Check
    wandb: False                                     # < Check
    save: False                                      # < Check
    break_train_iter: False                         # < Check
    break_test_iter: False                          # < Check
    test_every_n_epochs: 1
  seed: 420
  hpsamp: ""

# Experiment Global Data Specifications (defines what an example is)
data:  # describing project-wide data specifications
  kits18:
    path: '/afs/crc.nd.edu/user/y/yzhang46/datasets/KiTS-2019/'
  
  segdecathlon:
    path: '/afs/crc.nd.edu/user/y/yzhang46/datasets/MedicalSegmentationDecathlon/'

# Training Specifications
train:
  start_epoch: 0
  epochs: 60
  batch_size: 96
  
  optimizer:
    name: 'adam'  # sgd, nesterov, adam
    lr: .0002
    momentum: 0 # 0.9
    wt_decay: 0 # 0.0001
    adam:
      betas: [0.9, 0.999]
     
  scheduler:
    name: 'exponential'  # 'consistencycosine'
    rampup_rates: []
    min_lr: 0.000001
    exponential:
      exp_factor: 0.92
    consistencycosine:


# Model / Criterion / Other nn.Module Specifications
model:
  name: 'densenet'
  ema: False
  ema_drop: False
  alpha: 0.99
  num_classes: -1

  densenet:
    name: 'densenet121'
    pretrained: True
    only_encoder: False
    layer_drop_rate: 0.
    final_drop_rate: 0.2
    
  resnet:
    name: 'resnet34'
    pretrained: True
    final_drop_rate: 0.2

  efficientnet:
    name: 'efficientnetb0'
    pretrained: True

lab_criterion:
  name: 'hard_ce'
  hard_ce:
    weights: False  # weights are stored in experiments/setup.py
    reduction: 'mean'

unlab_criterion:
  name: 'hard_ce'
  weight: 1  # λ_u
  thresh: 0.95  # τ
  T: 1  # softmax temperature (softmax(logit/T))
  hard_ce:
    weights: False
    reduction: 'none'
  soft_ce:
    weights: False
  softmax_mse:
    weights: False

  
    
  